name: indexed_list_view
description: Similar to a ListView, but lets you programmatically jump instantly to any item, by index. Performant for lists of any size.
version: 1.0.8
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/indexed_list_view

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
